create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  image_path text not null,
  predicted_class text not null,
  confidence double precision not null,
  explanation text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  prediction_id bigint not null references public.predictions(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.chats(id) on delete cascade,
  role text not null,
  message text not null,
  created_at timestamptz not null default timezone('utc', now())
);
